version: '3'
services:
  app:
    build: .
    image: blogger
    command: make run
    container_name: blogger_container
    volumes:
      # Bind mount current host directory with /blogger volume in container.
      # This will override /blogger in container with the host directory
      # content and changes in one will be reflected in other.
      - .:/blogger
      # Create volume from node_modules/ directory in the image. This will bind
      # node_modules/ volume with a directory somewhere under
      # /var/lib/docker/volumes on the host. Here the node_modules/ directory
      # will not be overridden with host directory's content.
      - /blogger/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "18660:18660"
