extends: google
parserOptions:
  ecmaVersion: 6
env:
  node: true
  es6: true
rules:
  valid-jsdoc:
  - error
  - requireReturn: true
    requireReturnType: true
    requireParamDescription: true
    requireReturnDescription: true
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: true
      MethodDefinition: true
      ClassDeclaration: true
