version: '3'
services:
  app:
    build: .
    image: blogger_v2
    command: make run
    container_name: blogger_v2_container
    volumes:
      - .:/blogger
      - /blogger/node_modules
    environment:
      NODE_ENV: dev
    ports:
      - "18660:18660"
